In [43]:
import pandas as pd

df =pd.read_csv('Phishing_Email.csv')
df.head()

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email

In [44]:
print(df.columns)
df =df.dropna(subset=['Email Text'])

Index(['Unnamed: 0', 'Email Text', 'Email Type'], dtype='object')

In [45]:
dummies = pd.get_dummies(df['Email Type'])
merged = pd.concat([df,dummies],axis='columns')
final = merged.drop(['Email Type','Unnamed: 0'],axis='columns')
final.head()

,Email Text,Phishing Email,Safe Email
0,"re : 6 . 1100 , disc : uniformitarianism , re ...",False,True
1,the other side of * galicismos * * galicismo *...,False,True
2,re : equistar deal tickets are you still avail...,False,True
3,\nHello I am your hot lil horny toy.\n I am...,True,False
4,software at incredibly low prices ( 86 % lower...,True,False

In [46]:
final['label'] = merged['Phishing Email'].astype(int)
final = final.drop(['Phishing Email','Safe Email'],axis = 1)
final.head()

                                          Email Text  label
0  re : 6 . 1100 , disc : uniformitarianism , re ...      0
1  the other side of * galicismos * * galicismo *...      0
2  re : equistar deal tickets are you still avail...      0
3  \nHello I am your hot lil horny toy.\n    I am...      1
4  software at incredibly low prices ( 86 % lower...      1

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [48]:
x=final['Email Text']
y=final['label']

In [49]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

In [51]:
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)
x_train_vec = vectorizer.fit_transform(x_train)
x_test_vec = vectorizer.transform(x_test)

In [52]:
model = LogisticRegression()
model.fit(x_train_vec, y_train)

LogisticRegression()

In [53]:
y_pred = model.predict(x_test_vec)

In [54]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9688757713979071

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.96      0.97      2274
           1       0.94      0.98      0.96      1453

    accuracy                           0.97      3727
   macro avg       0.96      0.97      0.97      3727
weighted avg       0.97      0.97      0.97      3727

In [55]:
import joblib
joblib.dump(model, 'Phishing_model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')

['vectorizer.pkl']